name: Deploy AOS Process

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Download deps
        working-directory: deploy
        run: |
          npm i

      - name: Deploy AOS Process
        working-directory: deploy
        run: node index.js
        env:
          KEYFILE: ${{ secrets.KEYFILE }}
          AOS: ${{ secrets.AOS }}
